# Generated by Django 4.2 on 2024-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_code", models.CharField(max_length=3, verbose_name="CharCode")),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название валюты"),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "ordering": ["id"],
            },
        ),
    ]
