# Generated by Django 4.2 on 2024-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide_currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="char_code",
            field=models.CharField(max_length=3, unique=True, verbose_name="CharCode"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название валюты"
            ),
        ),
    ]
