# Generated by Django 4.2 on 2024-05-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guide_currency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRatesModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="дата")),
                ("value", models.DecimalField(decimal_places=4, max_digits=9)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="guide_currency.currency",
                        verbose_name="id_валюты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валют",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["id"],
            },
        ),
    ]
