# Generated by Django 4.2 on 2024-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeratesmodels",
            name="date",
            field=models.DateField(unique=True, verbose_name="дата"),
        ),
    ]
