# Generated by Django 4.2 on 2024-05-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide_currency", "0002_alter_currency_char_code_alter_currency_name"),
        ("exchange_rates", "0002_alter_exchangeratesmodels_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExchangeRatesModels",
            new_name="ExchangeRates",
        ),
    ]
