# Generated by Django 4.2 on 2024-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0003_rename_exchangeratesmodels_exchangerates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerates",
            name="date",
            field=models.DateField(verbose_name="дата"),
        ),
    ]
